### ISSUE TITLE
Unit tests support

### ISSUE THREAD

**Issue by pmarjan-onestic** [Adyen/adyen-magento2-hyva#36]
The Adyen_Hyva module should be supported with PHP unit tests. 
All PHP files should be supported in this kind of way.
Work would be done on a separate branch checkout out from the main one, and subsequently a PR will be opened for review purposes.

Side notes: 
In a weekly meet, we have discarded the need of api-functional and integration tests, deciding to add only Unit tests as a complement to the end-to-end tests.

**Comment by candemiralp** [comment]
Unit test have been added and test workflow has been activated. Closing this issue.
