### ISSUE TITLE
Feature: Klarna support?

### ISSUE THREAD

**Issue by amenk** [Adyen/adyen-magento2-hyva#42]
When is Klarna support planned?

**Comment by RokPopov** [comment]
Hi @amenk,

Thank you for your question. Currently, we are supporting Klarna Pay Later, however we are working on adding other local payment methods. You can follow [this Github Issue](https://github.com/Adyen/adyen-magento2-hyva/issues/43) for that. I am closing this ticket as of now. 

Kind regards,
Rok
