### ISSUE TITLE
[ECP-9218] Alternative Payments Methods

### ISSUE THREAD

**Issue by DanieliMi** [Adyen/adyen-magento2-hyva#43]
Alternative payment methods are currently not listed in the supported payment methods in the [readme](https://github.com/Adyen/adyen-magento2-hyva?tab=readme-ov-file#supported-methods).

Do you plan to include them? If so do you already know when you will support them?

**Comment by RokPopov** [comment]
Hi @DanieliMi,

Thank you for reaching out to us about this. Currently, we are working on adding more payment methods to bring the PM coverage closer to what is supported in the default plugin. Please note there is no ETA, however the task is being worked on as we speak. Once the PR will be merged, we will update this issue accordingly.

Kind regards,
Rok

**Comment by DanieliMi** [comment]
Hi @RokPopov,
alright, thanks for the info!

**Comment by amenk** [comment]
For the record: https://github.com/Adyen/adyen-magento2-hyva/pull/44

@RokPopov Thanks for the feedback.
