### ISSUE TITLE
[ECP-9547] Problem with Klarna PayOne

### ISSUE THREAD

**Issue by Taran00** [Adyen/adyen-magento2-hyva#71]
**Describe the bug**
It seems that I cannot use Klarna PayNow as a payment method. The issue is caused by missing data (invoiceLines) required for the payment to be processed.

**To Reproduce**
1. Go to checkout and try to pay via Klarna PayNow
2. See error The Payment is Refused

**Expected behavior**
I should be redirected to the Klarna Gateway and able to complete the payment.

**Magento version**
2.4.6-p4

**Plugin version**
1.2.1

**Additional context**
I believe this payment method should work similarly to the default Klarna payment method. It seems that there’s a missing observer to add the correct BrandCode (similar to the BrandCodeDataAssigner). Without this, the required additional data for Klarna PayNow payments is not attached.

For test purposes, I have temporarily hardcoded the BrandCode value as 'klarna' during payment process, and with this modification, everything looks fine.

**Comment by khushboo-singhvi** [comment]
Hello @Taran00,

Thank you for bringing this to our attention. We’ve created an internal ticket to investigate this issue further and are actively working on a resolution. We’ll keep you updated on any progress and let you know as soon as we have more information.

If you have additional details that might help our investigation, please feel free to share them here.

Thank you for your patience and understanding.

Regards!
Khushboo
